### ISSUE TITLE
Incorrect distance name does not break the computation 

### ISSUE THREAD

**Issue by droodev** [szufix/mapel#19]
I passed ```"swap"``` as a ```distance_id``` parameter to ```compute_distances```. Instead of crashing and blaming the user, the program continued to compute stuff, returning None. Here, I'd expect the fail-fast approach. I attach a screenshot of the snipped of code where the problem occurs. Basically, it should not take the path printing out "Hey, hey".

![image](https://user-images.githubusercontent.com/7488821/175917217-7c96707a-e51b-4ff6-9a51-f9c3bfeb06cb.png)

**Comment by szufix** [comment]
Solved.
